### ISSUE TITLE
error when compiling with latest frege

### ISSUE THREAD

**Issue by roti** [mmhelloworld/fregelet#6]
Compiling fails with latest frege 3.24.100.1:

```
E FregeletServlet.fr:137: implementation
    of `Handler.pure` must be supplied.
E FregeletServlet.fr:138: instance
    member function `Monad_Handler.return` is not a
    class member function
```

I have too little Haskell knowlegde to know what this actually means.

**Comment by mmhelloworld** [comment]
Hi,

Thanks for reporting this. Apparently it hasn't been tested with 3.24.100.1 yet. I will try to get this done in this week.
